version: "3.1"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_URI: mysql://user:password@db:3306/db
    ports:
      - "3306:3306"
    volumes:
      - ~/data:/var/lib/mysql
    networks:
      - default
